### ISSUE TITLE
Infobox

### ISSUE THREAD

**Issue by rhersel** [Opentronix/Opentronix#3]
Create an infobox that can be attached to the right panel (under the tag widget).
The infobox may contain simple (ASCII) or HTML text to display important information constantly to all users, for example an announcement of the next event (Stammtisch). The content of the infobox must be easily maintainable (just enter the text) with Admin rights or by members of a private group.

**Comment by Mannshoch** [comment]
The Info Box will contain in most situation data about next events. So it could maybe get the Date from an Ics File. It should Prompt the next three events.

**Comment by Opentronix** [comment]
Solved, thanks @eliasdiem
